### ISSUE TITLE
change data and only five circles are displayed

### ISSUE THREAD

**Issue by akiori** [tibotiber/rfd-update-example#1]
change data and only five circles are displayed (the same as dataset0), but in fact, there are eight (dataset1)
maybe in line 101, you only bind 5 array elements?

**Comment by pavloDeshko** [comment]
in v4 one should merge() enter selection back to one given by data(). otherwise appends are lost
also fixing this exposed that apparently v4 can't interpolate properly from nonexistent attribute, so some of them must be assigned before the transition

**Comment by tibotiber** [comment]
@pavloDeshko has nailed it! Please check his PR for fix, will be merged soon.

**Comment by tibotiber** [comment]
fix was merged
